Update Dockerfile.template

diff --git a/Dockerfile.template b/Dockerfile.template
--- a/Dockerfile.template
+++ b/Dockerfile.template
@@ -161,123 +161,92 @@ RUN set -eux; \
 # excluding opcache due https://github.com/docker-library/wordpress/issues/407
 {{ ) end -}}
 # https://wordpress.org/support/article/editing-wp-config-php/#configure-error-logging
+
 RUN { \
-# https://www.php.net/manual/en/errorfunc.constants.php
-# https://github.com/docker-library/wordpress/issues/420#issuecomment-517839670
-		echo 'error_reporting = E_ERROR | E_WARNING | E_PARSE | E_CORE_ERROR | E_CORE_WARNING | E_COMPILE_ERROR | E_COMPILE_WARNING | E_RECOVERABLE_ERROR'; \
-		echo 'display_errors = Off'; \
-		echo 'display_startup_errors = Off'; \
-		echo 'log_errors = On'; \
-		echo 'error_log = /dev/stderr'; \
-		echo 'log_errors_max_len = 1024'; \
-		echo 'ignore_repeated_errors = On'; \
-		echo 'ignore_repeated_source = Off'; \
-		echo 'html_errors = Off'; \
-	} > /usr/local/etc/php/conf.d/error-logging.ini
-{{ if env.variant == "apache" then ( -}}
+    # https://www.php.net/manual/en/errorfunc.constants.php
+    # https://github.com/docker-library/wordpress/issues/420#issuecomment-517839670
+    echo 'error_reporting = E_ERROR | E_WARNING | E_PARSE | E_CORE_ERROR | E_CORE_WARNING | E_COMPILE_ERROR | E_COMPILE_WARNING | E_RECOVERABLE_ERROR'; \
+    echo 'display_errors = Off'; \
+    echo 'display_startup_errors = Off'; \
+    echo 'log_errors = On'; \
+    echo 'error_log = /dev/stderr'; \
+    echo 'log_errors_max_len = 1024'; \
+    echo 'ignore_repeated_errors = On'; \
+    echo 'ignore_repeated_source = Off'; \
+    echo 'html_errors = Off'; \
+} > /usr/local/etc/php/conf.d/error-logging.ini
+
+# Configuração para o Nginx
+RUN set -eux; \
+    # Install necessary packages for Nginx
+    apt-get update && apt-get install -y nginx; \
+    \
+    # Configure Nginx to serve WordPress
+    { \
+        echo 'server {'; \
+        echo '    listen 80 default_server;' \
+        echo '    root /var/www/html;' \
+        echo '    index index.php index.html index.htm;' \
+        echo '    server_name _;' \
+        echo '    location / {'; \
+        echo '        try_files $uri $uri/ /index.php?$args;'; \
+        echo '    }'; \
+        echo '    location ~ \.php$ {'; \
+        echo '        include snippets/fastcgi-php.conf;' \
+        echo '        fastcgi_pass 127.0.0.1:9000;' \
+        echo '        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;' \
+        echo '        include fastcgi_params;' \
+        echo '    }'; \
+        echo '}'; \
+    } > /etc/nginx/sites-available/default; \
+    \
+    # Enable and start Nginx
+    service nginx start
 
 RUN set -eux; \
-	a2enmod rewrite expires; \
-	\
-# https://httpd.apache.org/docs/2.4/mod/mod_remoteip.html
-	a2enmod remoteip; \
-	{ \
-		echo 'RemoteIPHeader X-Forwarded-For'; \
-# these IP ranges are reserved for "private" use and should thus *usually* be safe inside Docker
-		echo 'RemoteIPInternalProxy 10.0.0.0/8'; \
-		echo 'RemoteIPInternalProxy 172.16.0.0/12'; \
-		echo 'RemoteIPInternalProxy 192.168.0.0/16'; \
-		echo 'RemoteIPInternalProxy 169.254.0.0/16'; \
-		echo 'RemoteIPInternalProxy 127.0.0.0/8'; \
-	} > /etc/apache2/conf-available/remoteip.conf; \
-	a2enconf remoteip; \
-# https://github.com/docker-library/wordpress/issues/383#issuecomment-507886512
-# (replace all instances of "%h" with "%a" in LogFormat)
-	find /etc/apache2 -type f -name '*.conf' -exec sed -ri 's/([[:space:]]*LogFormat[[:space:]]+"[^"]*)%h([^"]*")/\1%a\2/g' '{}' +
-{{ ) else "" end -}}
-
-{{ if env.version != "cli" then ( -}}
-RUN set -eux; \
-	version={{ .upstream | @sh }}; \
-	sha1={{ .sha1 | @sh }}; \
-	\
-	curl -o wordpress.tar.gz -fL "https://wordpress.org/wordpress-$version.tar.gz"; \
-	echo "$sha1 *wordpress.tar.gz" | sha1sum -c -; \
-	\
-# upstream tarballs include ./wordpress/ so this gives us /usr/src/wordpress
-	tar -xzf wordpress.tar.gz -C /usr/src/; \
-	rm wordpress.tar.gz; \
-	\
-# https://wordpress.org/support/article/htaccess/
-	[ ! -e /usr/src/wordpress/.htaccess ]; \
-	{ \
-		echo '# BEGIN WordPress'; \
-		echo ''; \
-		echo 'RewriteEngine On'; \
-		echo 'RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]'; \
-		echo 'RewriteBase /'; \
-		echo 'RewriteRule ^index\.php$ - [L]'; \
-		echo 'RewriteCond %{REQUEST_FILENAME} !-f'; \
-		echo 'RewriteCond %{REQUEST_FILENAME} !-d'; \
-		echo 'RewriteRule . /index.php [L]'; \
-		echo ''; \
-		echo '# END WordPress'; \
-	} > /usr/src/wordpress/.htaccess; \
-	\
-	chown -R www-data:www-data /usr/src/wordpress; \
-# pre-create wp-content (and single-level children) for folks who want to bind-mount themes, etc so permissions are pre-created properly instead of root:root
-# wp-content/cache: https://github.com/docker-library/wordpress/issues/534#issuecomment-705733507
-	mkdir wp-content; \
-	for dir in /usr/src/wordpress/wp-content/*/ cache; do \
-		dir="$(basename "${dir%/}")"; \
-		mkdir "wp-content/$dir"; \
-	done; \
-	chown -R www-data:www-data wp-content; \
-	chmod -R 1777 wp-content
-{{ ) else ( -}}
-# https://make.wordpress.org/cli/2018/05/31/gpg-signature-change/
-# pub   rsa2048 2018-05-31 [SC]
-#       63AF 7AA1 5067 C056 16FD  DD88 A3A2 E8F2 26F0 BC06
-# uid           [ unknown] WP-CLI Releases <releases@wp-cli.org>
-# sub   rsa2048 2018-05-31 [E]
-ENV WORDPRESS_CLI_GPG_KEY 63AF7AA15067C05616FDDD88A3A2E8F226F0BC06
-
-ENV WORDPRESS_CLI_VERSION {{ .version }}
-ENV WORDPRESS_CLI_SHA512 {{ .sha512 }}
-
-RUN set -ex; \
-	\
-	apk add --no-cache --virtual .fetch-deps \
-		gnupg \
-	; \
-	\
-	curl -o /usr/local/bin/wp.gpg -fL "https://github.com/wp-cli/wp-cli/releases/download/v${WORDPRESS_CLI_VERSION}/wp-cli-${WORDPRESS_CLI_VERSION}.phar.gpg"; \
-	\
-	GNUPGHOME="$(mktemp -d)"; export GNUPGHOME; \
-	gpg --batch --keyserver keyserver.ubuntu.com --recv-keys "$WORDPRESS_CLI_GPG_KEY"; \
-	gpg --batch --decrypt --output /usr/local/bin/wp /usr/local/bin/wp.gpg; \
-	gpgconf --kill all; \
-	rm -rf "$GNUPGHOME" /usr/local/bin/wp.gpg; unset GNUPGHOME; \
-	\
-	echo "$WORDPRESS_CLI_SHA512 */usr/local/bin/wp" | sha512sum -c -; \
-	chmod +x /usr/local/bin/wp; \
-	\
-	apk del --no-network .fetch-deps; \
-	\
-	wp --allow-root --version
-{{ ) end -}}
+    version={{ .upstream | @sh }}; \
+    sha1={{ .sha1 | @sh }}; \
+    \
+    curl -o wordpress.tar.gz -fL "https://wordpress.org/wordpress-$version.tar.gz"; \
+    echo "$sha1 *wordpress.tar.gz" | sha1sum -c -; \
+    \
+    # upstream tarballs include ./wordpress/ so this gives us /usr/src/wordpress
+    tar -xzf wordpress.tar.gz -C /usr/src/; \
+    rm wordpress.tar.gz; \
+    \
+    # https://wordpress.org/support/article/htaccess/
+    [ ! -e /usr/src/wordpress/.htaccess ]; \
+    { \
+        echo '# BEGIN WordPress'; \
+        echo ''; \
+        echo 'RewriteEngine On'; \
+        echo 'RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]'; \
+        echo 'RewriteBase /'; \
+        echo 'RewriteRule ^index\.php$ - [L]'; \
+        echo 'RewriteCond %{REQUEST_FILENAME} !-f'; \
+        echo 'RewriteCond %{REQUEST_FILENAME} !-d'; \
+        echo 'RewriteRule . /index.php [L]'; \
+        echo ''; \
+        echo '# END WordPress'; \
+    } > /usr/src/wordpress/.htaccess; \
+    \
+    chown -R www-data:www-data /usr/src/wordpress; \
+    # pre-create wp-content (and single-level children) for folks who want to bind-mount themes, etc so permissions are pre-created properly instead of root:root
+    # wp-content/cache: https://github.com/docker-library/wordpress/issues/534#issuecomment-705733507
+    mkdir wp-content; \
+    for dir in /usr/src/wordpress/wp-content/*/ cache; do \
+        dir="$(basename "${dir%/}")"; \
+        mkdir "wp-content/$dir"; \
+    done; \
+    chown -R www-data:www-data wp-content; \
+    chmod -R 1777 wp-content
 
 VOLUME /var/www/html
 
-{{ if env.version != "cli" then ( -}}
+# Adicionar configuração wp-config-docker.php para WordPress
 COPY --chown=www-data:www-data wp-config-docker.php /usr/src/wordpress/
-{{ ) else "" end -}}
+
 COPY docker-entrypoint.sh /usr/local/bin/
 
 ENTRYPOINT ["docker-entrypoint.sh"]
-{{ if env.version != "cli" then ( -}}
-CMD {{ [ if env.variant == "apache" then "apache2-foreground" else "php-fpm" end ] | @json }}
-{{ ) else ( -}}
-USER www-data
-CMD ["wp", "shell"]
-{{ ) end -}}
+CMD ["php-fpm"]
